[package]
name = "proto-gen"
authors = ["Mike Nguyen <hey@mike.ee>"]
license = "Apache-2.0"
edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
tonic-build = "0.11.0"
prost-types = "0.12.3"
prost-build = "0.13.1"
